[package]
name = "sx127"
version = "0.3.1"
authors = ["Your Mom"]
edition = "2018"

[dependencies]
embedded-hal = "~0.2"
bit_field = "~0.10"

[dev-dependencies]
rppal = { version = "0.14.1", features = ["hal"] }

[features]
default = ["fsk-ook"]
lora = []
fsk-ook = []
